# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodepenEmbedPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='codepenembed_codepenembedplugin', serialize=False, to='cms.CMSPlugin')),
                ('pen', models.CharField(max_length=6, verbose_name='Codepen identifier')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
