# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepenembed', '0002_codepenembedplugin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepenembedplugin',
            name='selected_language',
            field=models.CharField(blank=True, choices=[(b'html', b'HTML'), (b'css', b'CSS'), (b'js', b'JavaScript')], max_length=10, null=True, verbose_name='Taal'),
        ),
        migrations.AddField(
            model_name='codepenembedplugin',
            name='show_result',
            field=models.BooleanField(default=True, verbose_name='Show result'),
        ),
    ]
