# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='image_imageplugin', serialize=False, to='cms.CMSPlugin')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alternative text')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS class')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='afbeelding')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
